const assert = require('node:assert/strict');
const { loadNetworkConfig } = require('./network-config');
const root = require('../config/unon-networks.json');
process.env.DEPLOY_NETWORK = 'worldchain';
process.env.WORLD_CHAIN_CHAIN_ID = '480';
process.env.UNON_TOKEN_ADDRESS = '0x827F453646EE0622d122232f1CF00a10b1827Cd6';
process.env.WCT_ONBOARDING_MANAGER_ADDRESS = '0xE9c1c3ceE0EDaEA13081A177f1108839d0458083';
process.env.MIGRATION_MANAGER_ADDRESS = '0x42e53b6D69cd29Ed1D371FdCD61B986b273aA05D';
process.env.ONBOARDING_REWARDS_ENABLED = 'false';
const config = loadNetworkConfig();
assert.deepEqual(config.contracts, root.networks.worldchain.contracts);
assert.equal(config.publicConfig.features.onboarding, false);
assert.equal(config.publicConfig.features.migration, false);
assert.equal(config.deployment.startBlock, 35840349);
assert.equal(config.warnings.length, 3);
console.log('Replacement configuration: pinned addresses, disabled rewards/migration and new index origin passed.');
const fs = require('node:fs');
const path = require('node:path');
const app = fs.readFileSync(path.join(__dirname, '../src/App.tsx'), 'utf8');
assert.equal((app.match(/MiniKit\.sendTransaction\(/g) || []).length, 1, 'All sends must use the guarded entrypoint');
assert.equal((app.match(/await sendCurrentNetworkTransaction\(/g) || []).length, 6);
assert(app.includes('if (isChainConfigLoading || chainConfigError) throw new Error'));
assert(!app.includes('updateDoc('), 'Welcome reward profile changes must use the authenticated server');
console.log('All six active frontend transaction paths use the current-network guard (unused welcome handler removed).');
