async (page) => {
  const check = (condition, message) => { if (!condition) throw new Error(message); };
  const errors = [];
  const deletes = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.method() === 'DELETE') deletes.push(request.url()); });
  await page.unroute('**/api/challenges');
  await page.route('**/api/challenges', route => route.fulfill({contentType: 'application/json', path: 'tmp/discovery-live-snapshot.json'}));
  await page.goto('http://127.0.0.1:5174');
  await page.evaluate(() => { localStorage.setItem('challengeon-language', 'en'); localStorage.removeItem('challengeon-saved'); localStorage.removeItem('lastExpandedChallengeId'); });
  await page.reload();
  await page.locator('.on-card').first().waitFor();
  const baseline = await page.locator('.on-card').count();
  check(baseline > 10, 'Real trend snapshot must populate the feed');
  await page.getByRole('searchbox').fill('agenticai');
  check(await page.locator('.on-card').count() === 2, 'Search must match both existing AI trends');
  await page.locator('.save-challenge').first().click();
  await page.getByRole('button', {name: 'Saved', exact: true}).click();
  check(await page.locator('.on-card').count() === 1, 'Saved filter must narrow the feed');
  await page.reload();
  await page.locator('.on-card').first().waitFor();
  await page.getByRole('button', {name: 'Saved', exact: true}).click();
  check(await page.locator('.on-card').count() === 1, 'Saved IDs must survive reload');
  await page.getByRole('button', {name: 'Explore', exact: true}).click();
  await page.getByRole('combobox', {name: 'Platform', exact: true}).selectOption('tiktok');
  check(await page.locator('.on-card').count() > 0 && await page.locator('.on-card').count() < baseline, 'Platform filter must narrow the feed');
  await page.getByRole('combobox', {name: 'Sort challenges'}).selectOption('recent');
  await page.getByRole('searchbox').fill('no-such-challenge-xyz');
  await page.getByText('No matching challenges', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Reset filters'}).click();
  check(await page.locator('.on-card').count() === baseline, 'Reset must restore the feed');
  await page.getByRole('button', {name: 'Settings', exact: true}).click();
  const autoplay = page.getByRole('switch', {name: 'Autoplay videos'});
  await autoplay.uncheck();
  await page.getByRole('switch', {name: 'Start muted'}).check();
  await page.screenshot({path: 'tmp/experience-settings.png'});
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({state:'detached'});
  check(await page.getByRole('dialog').count() === 0, 'Escape must dismiss settings');
  check(await page.evaluate(() => localStorage.getItem('challengeon-autoplay')) === 'false', 'Playback setting must persist');
  const id = await page.locator('.on-card-shell').first().getAttribute('id');
  let videoRequests = 0;
  await page.route('https://example.invalid/test.mp4', () => {});
  await page.route('**/api/challenge-videos', async route => {
    videoRequests++;
    if (videoRequests === 1) return route.fulfill({status: 503, contentType: 'application/json', body: '{}'});
    return route.fulfill({contentType: 'application/json', body: JSON.stringify({success:true,data:[{id:'local-video',platform:'youtube',video_url:'https://example.invalid/test.mp4',video_title:'Playback test'}]})});
  });
  await page.locator('.on-card-open').first().click();
  await page.getByText('Videos could not be loaded.', {exact: true}).waitFor();
  check(await page.locator('.video-card-wrapper').count() === 0, 'An error must not invent videos');
  await page.getByRole('button', {name: 'Try again', exact: true}).click();
  await page.locator('video').waitFor({state:'attached'});
  check(await page.locator('video').evaluate(video => !video.autoplay && video.muted), 'Autoplay and mute preferences must reach the player');
  await page.locator('video').evaluate(video => video.dispatchEvent(new Event('error')));
  await page.waitForTimeout(300);
  check(deletes.length === 0, 'Playback failure must never delete production data');
  await page.reload();
  await page.locator('.on-card-shell.expanded').waitFor();
  check(await page.locator('.on-card-shell.expanded').getAttribute('id') === id, 'Expanded challenge must restore');
  await page.getByRole('button', {name: 'Battle ON', exact: true}).last().click();
  await page.getByRole('heading', {name:'Battle ON'}).waitFor();
  await page.getByRole('button', {name: 'Now ON', exact: true}).click();
  await page.getByRole('heading', {name:'Now ON'}).waitFor();
  check(await page.getByRole('button', {name:'Join challenge',exact:true}).count() > 0, 'Now missions need a join action');
  await page.getByRole('button', {name: 'Trend ON', exact: true}).click();
  await page.getByRole('heading', {name:'Trend ON'}).waitFor();
  await page.route('**/api/rankings/donations?*', route => route.fulfill({status:503,contentType:'application/json',body:'{}'}));
  await page.getByRole('button', {name:'Ranking',exact:true}).click();
  await page.getByText('Ranking could not be loaded. Please try again.',{exact:true}).waitFor();
  await page.unroute('**/api/rankings/donations?*');
  await page.route('**/api/rankings/donations?*', route => route.fulfill({contentType:'application/json',body:JSON.stringify({success:true,data:[]})}));
  await page.getByRole('button',{name:'Try again',exact:true}).click();
  await page.getByText('No donation ranking data for this period yet.',{exact:true}).waitFor();
  await page.getByRole('button', {name: 'Trend ON', exact: true}).click();
  await page.unroute('**/api/challenge-videos');
  await page.evaluate(() => localStorage.removeItem('lastExpandedChallengeId'));
  await page.reload();
  await page.locator('.on-card').first().waitFor();
  for (const [width,height] of [[1440,900],[390,844],[320,740]]) {
    await page.setViewportSize({width,height});
    await page.waitForTimeout(400);
    const overflow = await page.evaluate(() => Array.from(document.querySelectorAll('.header, .discovery-toolbar, .on-card, .bottom-nav')).some(el => el.getBoundingClientRect().right > innerWidth + 1));
    check(!overflow, `Layout overflow at ${width}px`);
    await page.screenshot({path:`tmp/experience-${width}.png`});
  }
  await page.unroute('**/api/challenges');
  await page.route('**/api/challenges', route => route.fulfill({status:503,contentType:'application/json',body:'{}'}));
  await page.reload();
  await page.getByText('Challenges could not be refreshed. Please try again.', {exact:true}).waitFor();
  check(await page.locator('.on-empty').count() === 0, 'API failure must not look like an empty catalog');
  await page.unroute('**/api/challenges');
  await page.route('**/api/challenges', route => route.fulfill({contentType:'application/json',path:'tmp/discovery-live-snapshot.json'}));
  await page.getByRole('button', {name:'Try again',exact:true}).click();
  await page.locator('.on-card').first().waitFor();
  check(errors.length === 0, `Browser exceptions: ${errors.join(', ')}`);
  return {passed:true, baseline, videoRequests, deletes:deletes.length, viewports:[1440,390,320]};
}
